version: '3'

services:
  diyhue:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    restart: always
    stop_grace_period: 0s
    environment:
      - disableonlinediscover=true
      - DEBUG=true
      - MAC=00:00:00:00:00:00
      - IP=192.168.1.1
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
      - '1982:1982/udp'